#!/bin/bash

# Two versions:  Trim and Refresh.  Version 1 will simply trim down all unwanted (by me in this prototype) packages after factory reset.  V2 will refresh (possible stock replacements, new features and apps that are lightweight, etc.)

## First verify it's the correct device, then do 2x confirmation.

package:com.amazon.clouddrive.photos X1
package:com.lge.sizechangable.weather.platform X1
package:com.lge.wallpaper.nightsky X1
package:com.lge.vrplayer X1
package:com.lge.mirrorlink X1
package:com.lge.floatingbar X1
package:com.lge.cloudhub X1
package:com.lge.remote.lgairdrive X1
package:com.google.android.apps.docs.editors.sheets X1
package:com.google.android.apps.docs.editors.slides X1
package:com.lge.lifetracker X1
package:com.lge.smartshare.provider X1
package:com.lge.myplace.engine X1
package:com.google.android.marvin.talkback X1
package:com.lge.launcher2.theme.optimus X1
package:com.lge.gallery.vr.wallpaper X1
package:com.lge.ia.task.incalagent X1
package:com.instagram.android X1
package:com.lge.iftttmanager X1
package:com.lge.exchange X1
package:com.lge.voiceprint X1
package:com.lge.wallpaper.perspective X1
package:com.lge.lgworld X1
package:com.android.printspooler X1
package:com.android.dreams.basic X1
package:com.lge.video.vr.wallpaper X1
package:com.android.hotwordenrollment.tgoogle X1
package:com.lge.task X1
package:com.google.android.apps.cloudprint X1
package:com.lge.sizechangable.weather.theme.optimus X1
package:com.lge.signboard.settings X1
package:com.lge.smartsharepush X1
package:com.facebook.katana X1
package:com.lge.gallery.collagewallpaper X1
package:com.android.providers.partnerbookmarks X1
package:com.lge.qhelp.application X1
package:com.android.wallpaper.livepicker X1
package:com.android.apps.tag X1
package:com.facebook.orca X1
package:com.facebook.system X1
package:com.lge.provider.signboard X1
package:com.lge.sizechangable.weather X1
package:com.audible.application X1
package:com.google.vr.vrcore X1
package:com.lge.sizechangable.musicwidget.widget X1
package:com.lge.faceglance.enrollment X1
package:com.lookout X1
package:com.lge.email X1
package:com.facebook.appmanager X1
package:com.lge.signboard X1
package:com.lge.wallpaper.lightwave X1
package:com.amazon.aa.attribution X1
package:com.lge.ime.solution.handwriting X1
package:com.google.android.inputmethod.latin X1
package:com.lge.qmemoplus X1
